name: ðŸ› Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us resolve it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "When I try to start recording, the app crashes..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open the app
        2. Go to Settings
        3. Enable calibration
        4. Start recording
        5. App crashes
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The recording should start without crashing"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "The app crashes with an error message"
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this bug occur?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Once
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Model
      description: What device are you using?
      placeholder: "e.g., Google Pixel 6"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: What version of Android is your device running?
      placeholder: "e.g., Android 13"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of the app are you using?
      placeholder: "e.g., 1.1.0 or commit hash"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please include any relevant logs from `adb logcat`.
        You can obtain logs by running: `adb logcat -d > logs.txt`
      placeholder: |
        ```
        E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.motosensorlogger, PID: 12345
        java.lang.NullPointerException: Attempt to invoke virtual method...
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images or videos here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This started happening after..."

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided all required information
          required: true
        - label: I am using the latest version of the app
          required: false